name: 'Setup Python Environment'
description: 'Sets up Python, caches dependencies, and installs requirements'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    
    - name: Install dependencies
      shell: bash
      run: pip install -r requirements.txt
