name: Build and Deploy (Full)

on:
  workflow_dispatch:  # Manual trigger only for full rebuild
    inputs:
      reason:
        description: 'Reason for full rebuild'
        required: false
        default: 'Manual full rebuild'

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-full:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Fetch third-party dependencies (Leaflet.js)
        run: |
          python3 src/event_manager.py dependencies fetch
      
      - name: Verify dependencies
        run: |
          python3 src/event_manager.py dependencies check
      
      - name: Full site generation (inline CSS/JS)
        run: |
          python3 src/event_manager.py generate
      
      - name: Add deployment timestamp
        run: |
          TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
          sed -i "s/BUILD_TIMESTAMP_PLACEHOLDER/$TIMESTAMP/g" public/index.html
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-full
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
