#!/usr/bin/env python3
"""
Documentation Builder for KRWL HOF Community Events

Self-contained single-file documentation generator following KISS principle.
Everything in one file, no external templates, minimal dependencies.

Usage:
    python3 docs/build_docs.py --validate    # Validate only
    python3 docs/build_docs.py               # Build README.md
    
Can be called from CLI/TUI for documentation management.
"""

import json
from pathlib import Path
from datetime import datetime


# README template embedded as constant (KISS: everything in one file)
README_TEMPLATE = """# {app_name}

> {app_description}

[![PWA Ready](https://img.shields.io/badge/PWA-Ready-success)](https://web.dev/progressive-web_apps/)
[![Accessibility](https://img.shields.io/badge/A11y-Compliant-blue)](https://www.w3.org/WAI/WCAG21/quickref/)
[![Mobile First](https://img.shields.io/badge/Mobile-First-orange)](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps)

## 🎯 Overview

A **fullscreen, mobile-first** interactive map application for discovering community events near you.

### ✨ Key Features

{features_section}

## 🚀 Quick Start

```bash
# Clone and setup
git clone https://github.com/feileberlin/krwl-hof.git
cd krwl-hof
./download-libs.sh

# Run locally
cd static
python3 -m http.server 8000
```

Open http://localhost:8000

## ⚙️ Configuration

All settings in `static/config.json`:

```json
{config_json}
```

### Customizable Elements
{customizable_elements}

## 🧪 Testing

```bash
# Validate documentation
python3 docs/build_docs.py --validate

# Test scrapers
python3 test_scraper.py --verbose

# Test filters
python3 test_filters.py --verbose
```

## 📝 Project Structure

```
krwl-hof/
├── static/          # Deployment files (HTML, CSS, JS, config)
├── src/             # Python backend (scraping, generation)
├── docs/            # Documentation
└── README.md        # This file (auto-generated)
```

## 🤝 Contributing

1. Fork the repository
2. Make your changes
3. Run `python3 docs/build_docs.py` to update docs
4. Submit a pull request

---

*Last updated: {timestamp}*  
*Auto-generated by `docs/build_docs.py`*
"""


class DocumentationBuilder:
    """Simple, self-contained documentation builder"""
    
    def __init__(self, root_dir='.'):
        self.root_dir = Path(root_dir)
        self.static_dir = self.root_dir / 'static'
        self.config_file = self.static_dir / 'config.json'
    
    def validate_documentation(self):
        """Validate that required files exist"""
        issues = []
        
        # Check required files
        required_files = [
            'static/index.html',
            'static/js/app.js',
            'static/css/style.css',
            'static/config.json',
            'static/manifest.json'
        ]
        
        for file in required_files:
            if not (self.root_dir / file).exists():
                issues.append(f"Missing required file: {file}")
        
        # Check config has required sections
        if self.config_file.exists():
            with open(self.config_file, 'r') as f:
                config = json.load(f)
                # Only check sections that actually exist and are used
                required_sections = ['app', 'map']
                for section in required_sections:
                    if section not in config:
                        issues.append(f"Missing config section: {section}")
        else:
            issues.append("Missing config.json")
        
        return issues
    
    def extract_features(self):
        """Extract basic feature info from codebase"""
        features = []
        
        # Check for PWA
        if (self.static_dir / 'manifest.json').exists():
            features.append("📱 **PWA**: Installable as native app")
        
        # Check for map
        if (self.static_dir / 'js' / 'app.js').exists():
            features.append("🗺️ **Interactive Map**: Leaflet.js with event markers")
        
        # Check for responsive design
        if (self.static_dir / 'css' / 'style.css').exists():
            features.append("📱 **Responsive**: Mobile-first design")
        
        return features
    
    def build_customizable_elements(self, config):
        """Build list of customizable config elements"""
        elements = []
        elements.append("- **App name/description**: `config.app.*`")
        elements.append("- **Map settings**: `config.map.*`")
        
        if 'scraping' in config:
            elements.append("- **Scraping sources**: `config.scraping.sources[]`")
        if 'filtering' in config:
            elements.append("- **Event filtering**: `config.filtering.*`")
        if 'editor' in config:
            elements.append("- **Editor settings**: `config.editor.*`")
        
        return '\n'.join(elements)
    
    def build_readme(self):
        """Build README.md from embedded template"""
        # Load config
        config = {}
        if self.config_file.exists():
            with open(self.config_file, 'r') as f:
                config = json.load(f)
        
        app_name = config.get('app', {}).get('name', 'KRWL HOF Community Events')
        app_desc = config.get('app', {}).get('description', 'Community events viewer')
        
        # Extract features
        features = self.extract_features()
        features_section = '\n'.join(f"- {f}" for f in features) if features else "- Basic event viewer"
        
        # Build customizable elements
        customizable_elements = self.build_customizable_elements(config)
        
        # Format config JSON (truncate if too long for readability)
        config_json = json.dumps(config, indent=2, ensure_ascii=False)
        if len(config_json) > 2000:
            config_json = json.dumps({
                "app": config.get("app", {}),
                "map": config.get("map", {}),
                "...": "See static/config.json for full configuration"
            }, indent=2)
        
        # Fill template
        readme = README_TEMPLATE.format(
            app_name=app_name,
            app_description=app_desc,
            features_section=features_section,
            config_json=config_json,
            customizable_elements=customizable_elements,
            timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        )
        
        return readme
    
    def run(self, validate_only=False):
        """Run the documentation builder"""
        print("🔍 Validating documentation...")
        issues = self.validate_documentation()
        
        if issues:
            print("❌ Documentation validation failed:")
            for issue in issues:
                print(f"  - {issue}")
            return False
        
        print("✅ Documentation validation passed")
        
        if validate_only:
            return True
        
        print("📝 Building README.md...")
        readme_content = self.build_readme()
        
        # Write README
        readme_path = self.root_dir / 'README.md'
        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(readme_content)
        
        print(f"✅ README.md generated ({len(readme_content)} bytes)")
        return True


if __name__ == '__main__':
    import sys
    
    validate_only = '--validate' in sys.argv
    
    builder = DocumentationBuilder()
    success = builder.run(validate_only=validate_only)
    
    sys.exit(0 if success else 1)
