#!/usr/bin/env python3
"""
Design Token Generator

Reads design tokens from config.json and generates CSS custom properties.
This enables instant rebranding by editing the config and regenerating.

Usage:
    python3 src/tools/generate_design_tokens.py
    
Output:
    layouts/components/design-tokens.css
"""

import json
import sys
from pathlib import Path
from typing import Dict, List


def load_config(base_path: Path) -> Dict:
    """Load configuration file with design tokens"""
    config_file = base_path / 'config.json'
    if not config_file.exists():
        raise FileNotFoundError(f"Config file not found: {config_file}")
    
    with open(config_file, 'r', encoding='utf-8') as f:
        return json.load(f)


def validate_design_tokens(design: Dict) -> List[str]:
    """Validate design token structure and return any warnings"""
    warnings = []
    
    # Required sections
    required_sections = ['colors', 'typography', 'spacing', 'z_index', 
                        'shadows', 'borders', 'transitions', 'branding']
    
    for section in required_sections:
        if section not in design:
            warnings.append(f"Missing section: {section}")
    
    # Validate colors
    if 'colors' in design:
        colors = design['colors']
        required_colors = ['primary', 'bg_primary', 'text_primary']
        for color in required_colors:
            if color not in colors:
                warnings.append(f"Missing required color: {color}")
    
    return warnings


def convert_to_css_var_name(key: str) -> str:
    """Convert Python key to CSS variable name"""
    # Replace underscores with hyphens for CSS convention
    return key.replace('_', '-')


def generate_css_custom_properties(design: Dict) -> str:
    """Generate CSS custom properties from design tokens"""
    lines = [
        "/**",
        " * Design Tokens - Auto-generated CSS Custom Properties",
        " * Generated from config.json design section",
        " * ",
        " * DO NOT EDIT THIS FILE DIRECTLY",
        " * Run: python3 src/tools/generate_design_tokens.py",
        " */",
        "",
        ":root {",
        "  /* ====================================================================== */",
        "  /* DESIGN TOKENS - Generated from config.json */",
        "  /* ====================================================================== */",
        ""
    ]
    
    # Generate color tokens
    if 'colors' in design:
        lines.append("  /* Colors */")
        for key, value in design['colors'].items():
            css_var = convert_to_css_var_name(key)
            lines.append(f"  --color-{css_var}: {value};")
        lines.append("")
    
    # Generate typography tokens
    if 'typography' in design:
        lines.append("  /* Typography */")
        for key, value in design['typography'].items():
            css_var = convert_to_css_var_name(key)
            lines.append(f"  --{css_var}: {value};")
        lines.append("")
    
    # Generate spacing tokens
    if 'spacing' in design:
        lines.append("  /* Spacing */")
        for key, value in design['spacing'].items():
            css_var = convert_to_css_var_name(key)
            lines.append(f"  --spacing-{css_var}: {value};")
        lines.append("")
    
    # Generate z-index tokens
    if 'z_index' in design:
        lines.append("  /* Z-Index Layers (4-layer system) */")
        for key, value in design['z_index'].items():
            if key.startswith('_'):  # Skip comment keys
                continue
            css_var = convert_to_css_var_name(key)
            lines.append(f"  --z-{css_var}: {value};")
        lines.append("")
    
    # Generate shadow tokens
    if 'shadows' in design:
        lines.append("  /* Shadows */")
        for key, value in design['shadows'].items():
            css_var = convert_to_css_var_name(key)
            lines.append(f"  --shadow-{css_var}: {value};")
        lines.append("")
    
    # Generate border tokens
    if 'borders' in design:
        lines.append("  /* Borders */")
        for key, value in design['borders'].items():
            css_var = convert_to_css_var_name(key)
            lines.append(f"  --border-{css_var}: {value};")
        lines.append("")
    
    # Generate transition tokens
    if 'transitions' in design:
        lines.append("  /* Transitions */")
        for key, value in design['transitions'].items():
            css_var = convert_to_css_var_name(key)
            lines.append(f"  --transition-{css_var}: {value};")
        lines.append("")
    
    lines.append("}")
    lines.append("")
    
    # Add utility classes for common patterns
    lines.extend([
        "/* Overlay positioning classes */",
        ".overlay {",
        "  position: fixed;",
        "  background: var(--color-bg-secondary);",
        "  border: var(--border-width-thin) solid var(--color-border-primary);",
        "  border-radius: var(--border-radius-medium);",
        "  box-shadow: var(--shadow-medium);",
        "}",
        "",
        ".overlay--layer-3 {",
        "  z-index: var(--z-layer-3-ui);",
        "}",
        "",
        ".overlay--layer-4 {",
        "  z-index: var(--z-layer-4-modals);",
        "}",
        "",
        ".overlay--top-left {",
        "  top: var(--spacing-md);",
        "  left: var(--spacing-md);",
        "}",
        "",
        ".overlay--top-center {",
        "  top: var(--spacing-md);",
        "  left: 50%;",
        "  transform: translateX(-50%);",
        "}",
        "",
        ".overlay--top-right {",
        "  top: var(--spacing-md);",
        "  right: var(--spacing-md);",
        "}",
        ""
    ])
    
    return '\n'.join(lines)


def main():
    """Main function"""
    print("=" * 60)
    print("🎨 Design Token Generator")
    print("=" * 60)
    
    # Get base path (project root)
    base_path = Path(__file__).parent.parent.parent
    print(f"\nProject root: {base_path}")
    
    # Load config
    print("Loading config.json...")
    try:
        config = load_config(base_path)
    except FileNotFoundError as e:
        print(f"❌ Error: {e}")
        return 1
    
    if 'design' not in config:
        print("❌ Error: No 'design' section found in config.json")
        return 1
    
    design = config['design']
    print(f"✓ Found design section with {len(design)} categories")
    
    # Validate design tokens
    print("\nValidating design tokens...")
    warnings = validate_design_tokens(design)
    if warnings:
        print("⚠️  Warnings:")
        for warning in warnings:
            print(f"   - {warning}")
    else:
        print("✓ Design tokens are valid")
    
    # Generate CSS
    print("\nGenerating CSS custom properties...")
    css = generate_css_custom_properties(design)
    
    # Write output
    output_file = base_path / 'layouts' / 'components' / 'design-tokens.css'
    output_file.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(css)
    
    # Count tokens
    token_count = css.count('--')
    
    print(f"✓ Generated {token_count} CSS custom properties")
    print(f"\n✅ Output: {output_file}")
    print(f"   Size: {len(css) / 1024:.1f} KB")
    print("\n" + "=" * 60)
    print("🎨 Design tokens generated successfully!")
    print("=" * 60)
    
    # Show sample usage
    print("\n💡 Usage in CSS:")
    print("   color: var(--color-primary);")
    print("   background: var(--color-bg-primary);")
    print("   font-family: var(--font-family-base);")
    print("   padding: var(--spacing-md);")
    print("   z-index: var(--z-layer-3-ui);")
    print("\n💡 Instant Rebranding Workflow:")
    print("   1. Edit design section in config.json")
    print("   2. Run: python3 src/tools/generate_design_tokens.py")
    print("   3. Run: python3 src/event_manager.py generate")
    print("   4. Deploy!")
    
    return 0


if __name__ == '__main__':
    sys.exit(main())
