#!/usr/bin/env python3
"""
Migrate assets/css/style.css to use design tokens from config.json

Replaces old custom properties with design token variables while
maintaining backward compatibility.

Usage:
    python3 scripts/migrate_css_to_tokens.py [--dry-run]
"""

import sys
import re
from pathlib import Path


def migrate_css_to_tokens(css_content: str, dry_run: bool = False) -> str:
    """Migrate CSS to use design tokens"""
    
    lines = css_content.split('\n')
    output_lines = []
    in_root_block = False
    root_brace_count = 0
    
    for i, line in enumerate(lines):
        # Detect :root block start
        if line.strip() == ':root {':
            in_root_block = True
            root_brace_count = 1
            # Skip old :root block - we'll add comment about design tokens
            output_lines.append('/* CSS Custom Properties are now generated from config.json design tokens */')
            output_lines.append('/* See: assets/html/design-tokens.css */')
            output_lines.append('/* Generated by: python3 src/tools/generate_design_tokens.py */')
            output_lines.append('')
            output_lines.append('/* Import design tokens - these are inlined during site generation */')
            output_lines.append('/* Design tokens provide: colors, typography, spacing, z-index, shadows, borders, transitions */')
            output_lines.append('')
            continue
        
        # Track braces in :root block
        if in_root_block:
            root_brace_count += line.count('{') - line.count('}')
            if root_brace_count == 0:
                in_root_block = False
            continue  # Skip all lines in :root block
        
        # Now replace variable usages in the rest of the file
        modified_line = line
        
        # Map old variables to new design token names
        var_mappings = {
            # Barbie theme colors (keep for now - these are theme-specific)
            # We'll keep --barbie-* variables as they're theme-specific
            
            # Semantic mappings to design tokens
            '--bg-primary': '--color-bg-primary',
            '--bg-secondary': '--color-bg-secondary',
            '--bg-tertiary': '--color-bg-tertiary',
            '--text-primary': '--color-text-primary',
            '--text-secondary': '--color-text-secondary',
            '--text-tertiary': '--color-text-tertiary',
            '--accent-primary': '--color-primary',
            '--accent-hover': '--color-primary-hover',
            '--border-primary': '--color-border-primary',
            
            # Direct color mappings
            '--barbie-red': '--color-primary',
            '--barbie-red-hover': '--color-primary-hover',
            '--dark-grey': '--color-bg-primary',
            '--medium-dark': '--color-bg-secondary',
            '--medium-grey': '--color-bg-tertiary',
            '--white': '--color-text-primary',
            '--lighter-grey': '--color-text-tertiary',
        }
        
        for old_var, new_var in var_mappings.items():
            # Replace var(--old) with var(--new)
            modified_line = modified_line.replace(f'var({old_var})', f'var({new_var})')
        
        output_lines.append(modified_line)
    
    result = '\n'.join(output_lines)
    
    # Clean up multiple blank lines
    result = re.sub(r'\n\n\n+', '\n\n', result)
    
    return result


def main():
    """Main function"""
    import argparse
    
    parser = argparse.ArgumentParser(description='Migrate CSS to design tokens')
    parser.add_argument('--dry-run', action='store_true', help='Show changes without applying')
    args = parser.parse_args()
    
    base_path = Path(__file__).parent.parent
    css_file = base_path / 'assets' / 'css' / 'style.css'
    
    print("=" * 60)
    print("🎨 CSS Migration to Design Tokens")
    print("=" * 60)
    print(f"\nFile: {css_file}")
    
    # Read original
    original = css_file.read_text(encoding='utf-8')
    
    # Migrate
    print("\n📝 Migrating CSS variables...")
    migrated = migrate_css_to_tokens(original, dry_run=args.dry_run)
    
    # Show changes
    original_lines = original.split('\n')
    migrated_lines = migrated.split('\n')
    
    print(f"\nOriginal: {len(original_lines)} lines, {len(original)} bytes")
    print(f"Migrated: {len(migrated_lines)} lines, {len(migrated)} bytes")
    
    if args.dry_run:
        print("\n🔍 DRY RUN - Changes preview:")
        print("\nOld variables → New design tokens:")
        print("  --bg-primary → --color-bg-primary")
        print("  --text-primary → --color-text-primary")
        print("  --accent-primary → --color-primary")
        print("  --barbie-red → --color-primary")
        print("  ... and more")
        print("\nRun without --dry-run to apply changes")
    else:
        # Write migrated version
        css_file.write_text(migrated, encoding='utf-8')
        print("\n✅ Migration complete!")
        print("\n💡 Next steps:")
        print("  1. Regenerate site: python3 src/event_manager.py generate")
        print("  2. Test locally: cd static && python3 -m http.server 8000")
        print("  3. Verify visual appearance matches before migration")
    
    print("\n" + "=" * 60)
    return 0


if __name__ == '__main__':
    sys.exit(main())
